# Generated by Django 5.2.1 on 2025-06-25 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-creation_date'], 'verbose_name': 'orden', 'verbose_name_plural': 'órdenes'},
        ),
        migrations.AlterModelOptions(
            name='shipments',
            options={'ordering': ['-creation_date'], 'verbose_name': 'envío', 'verbose_name_plural': 'envíos'},
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.paymentstypes', verbose_name='Tipo de pago'),
        ),
        migrations.AddField(
            model_name='shipments',
            name='locality',
            field=models.CharField(default='EFE', max_length=50, verbose_name='Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipments',
            name='province',
            field=models.CharField(default='EFE', max_length=50, verbose_name='Provincia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='local_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección local'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.ordersstatus', verbose_name='Estado de la orden'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False, verbose_name='Número de seguimiento'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='confirmation_pin',
            field=models.PositiveIntegerField(verbose_name='Pin de confirmación'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.shipmentsstatus', verbose_name='Estado actual del envío'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False, verbose_name='Número de seguimiento'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
