# Generated by Django 5.2.1 on 2025-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='supplier_payment',
            field=models.BooleanField(default=False, verbose_name='Pago del proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='envelope_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Importe de sobre'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='local_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion local'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Importe total'),
        ),
    ]
