# Generated by Django 5.2.1 on 2025-06-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
