# Generated by Django 5.2.1 on 2025-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orders_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Importe total'),
        ),
    ]
